name: Generate Snake 

on:
  schedule:
    # Roda a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

# Permite que a Action escreva no repositório (CRUCIAL para o commit)
permissions:
  contents: write 
  
jobs:
  build:
    name: Build the snake svg
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout do código
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Geração da cobrinha
      - name: Generate the snake files in './dist/'
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # 3. Commit e Push dos arquivos gerados para o branch 'output'
      - name: Push new files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update snake animations"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
